### ISSUE TITLE
运行 _partion_aux_generate.py 时出现问题，求解答

### ISSUE THREAD

**Issue by lhy789** [baiyimeng/IFRU#1]
您好，感谢您和您的团队写出来如此高质量的开源代码，但我在运行时出现了如下问题，

[Traceback (most recent call last):
  File "IFRU/_partion_aux_generate.py", line 30, in <module>
    model.load_state_dict(torch.load(load_path))
  File "/lib/python3.9/site-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "lib/python3.9/site-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory](url)

这是否意味您的权重文件出了问题，如果您看见了，请您解答
我的 torch 版本是 2.0.1+cu117

**Comment by baiyimeng** [comment]
经过验证发现权重文件确实存在问题，后续会重新上传，感谢
